#config_version=6

mode:
  start_events: start_mode_bumpers
  stop_events: stop_mode_bumpers
  priority: 200

shots:
  shot_sling_left:
    switches: s_sling_left
  shot_sling_right:
    switches: s_sling_right
  shot_bumper_lower:
    switches: s_bumper_lower
  shot_bumper_upper:
    switches: s_bumper_upper
  shot_inlane_left:
    switches: s_inlane_left
  shot_inlane_right_1:
    switches: s_inlane_right_1
  shot_inlane_right_2:
    switches: s_inlane_right_2
  shot_scoop:
    switches: s_scoop_tina

shot_groups:
  slings:
    shots: shot_sling_left, shot_sling_right
  bumpers:
    shots: shot_bumper_lower, shot_bumper_upper
  inlanes:
    shots: shot_inlane_left, shot_inlane_right_1, shot_inlane_right_2

sound_player:
  slings_hit:
    gosh:
      bus: effects
     

variable_player:
  slings_hit:
    initial_value: 0
    score: 1_000
  bumpers_hit:
    initial_value: 0
    score: 10_000
  inlanes_hit:
    initial_value: 0
    score: 10
  shot_scoop_tina_hit:
    initial_value: 0
    score: 20_000