#config_version=6

switches:
  # Cabinet Switches
  s_flipper_left:
    number: #8
    tags: left_flipper
  s_flipper_right_lower:
    number: #16
    tags: right_flipper_lower
  s_flipper_right_upper:
    number: #17
    tags: right_flipper_upper
  s_start:
    number: #0
    tags: start

  #Trough Switches
  s_trough_1:
    number: #24
  s_trough_2: 
    number: #25
  s_trough_3:
    number: #26
  s_trough_4:
    number: #27
  s_trough_5:
    number: #28
  s_trough_6:
    number: #29
  s_trough_7:
    number: #30
    tags: trough_jam
  s_plunger_lane:
    number: #31

  #playfield switches
  s_sling_left:
    number: #40
    tags: left_sling
  s_sling_right:
    number: #33
    tags: right_sling
  s_bumper_lower:
    number: #41
    tags: lower_bumper
  s_bumper_upper:
    number: #42
    tags: upper_bumper
  s_inlane_right_1:
    number: #35
    tags: right_inlane_1
  s_inlane_right_2:
    number: #36
    tags: right_inlane_2
  s_inlane_left:
    number: #39
    tags: left_inlane

