#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.
#


hardware:
  platform: fast

fast:
  net:
    controller: neuron
    io_loop:
      cab_board: 
        model: FP-I/O-0024
        order: 1
      3208_middle:
        model: FP-I/O-3208
        order: 2
      0804_right:
        model: FP-I/O-0804
        order: 3
      #0804_left:
      #  model: FP-I/O-0804
      #  order: 4
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms

  exp:
    boards:
      neuron:
        model: FP-EXP-2000
  #      breakouts:
  #        - port: 1
  #          model: FP-PWR-0030

config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml

modes:
  - attract
  - base
  - bumpers
#  - hurryup

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

machine:
  balls_installed: 6
  min_balls: 6

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_flipper_left
    eos_switch: s_flipper_left_eos
    enable_events: mode_base_started #machine_reset_phase_3
  right_flipper_lower:
    main_coil: c_flipper_right_lower_main
    hold_coil: c_flipper_right_lower_hold
    activation_switch: s_flipper_right_lower
    eos_switch: s_flipper_right_lower_eos
    enable_events: mode_base_started #machine_reset_phase_3
  right_flipper_upper:
    main_coil: c_flipper_upper_main
    hold_coil: c_flipper_upper_hold
    activation_switch: s_flipper_right_upper
    eos_switch: s_flipper_right_upper_eos
    enable_events: mode_base_started #machine_reset_phase_3


#virtual_platform_start_active_switches:
#  - s_trough_1
#  - s_trough_2
#  - s_trough_3
#  - s_trough_4
#  - s_trough_5
#  - s_trough_6
#  - s_trough_7
  