#config_version=6

coils:
  c_trough_eject:
    number: 3208_middle-1
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 3208_middle-2
    allow_enable: true #The purpose of the allow_enable: true setting is that as a safety precaution, MPF does not allow you to enable (that is, to hold a coil in its "on" position) unless you specifically add allow_enable: true to that coil's config.
  c_flipper_left_main:
    number: 3208_middle-3
  c_flipper_right_lower_hold:
    number: 3208_middle-4
    allow_enable: true
  c_flipper_right_lower_main:
    number: 3208_middle-5
  c_sling_left:
    number: 3208_middle-6
  c_sling_right:
    number: 3208_middle-7
  c_flipper_upper_main:
    number: 0804_right-0
  c_flipper_upper_hold:
    number: 0804_right-1
    allow_enable: true
  c_scoop_tina:
    number: 0804_right-2

autofire_coils:
  left_sling:
    coil: c_sling_left
    switch: s_sling_left
  right_sling:
    coil: c_sling_right
    switch: s_sling_right  